"""add indexes for teachers high risk comments query

Revision ID: 011fc109782c
Revises: a7a8337332ef
Create Date: 2026-08-12 16:14:03.111997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "011fc109782c"
down_revision: Union[str, Sequence[str], None] = "a7a8337332ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_comments_evaluation_id"), "comments", ["evaluation_id"], unique=False
    )
    op.create_index(
        op.f("ix_comments_risk_level"), "comments", ["risk_level"], unique=False
    )
    op.create_index(
        op.f("ix_comments_teacher_id"), "comments", ["teacher_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comments_teacher_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_risk_level"), table_name="comments")
    op.drop_index(op.f("ix_comments_evaluation_id"), table_name="comments")
    # ### end Alembic commands ###
