"""add indexes for teachers with-averages query

Revision ID: 08f60f3e3cbc
Revises: 4527e7771321
Create Date: 2026-08-11 16:59:02.749457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f60f3e3cbc'
down_revision: Union[str, Sequence[str], None] = '4527e7771321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_academic_groups_teacher_id'), 'academic_groups', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_evaluation_scores_academic_group_id'), 'evaluation_scores', ['academic_group_id'], unique=False)
    op.create_index(op.f('ix_evaluations_academic_period_id'), 'evaluations', ['academic_period_id'], unique=False)
    op.create_index(op.f('ix_teachers_department_id'), 'teachers', ['department_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_department_id'), table_name='teachers')
    op.drop_index(op.f('ix_evaluations_academic_period_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluation_scores_academic_group_id'), table_name='evaluation_scores')
    op.drop_index(op.f('ix_academic_groups_teacher_id'), table_name='academic_groups')
    # ### end Alembic commands ###
