"""add ai model columns to comments

Revision ID: 0d2e7905869f
Revises: fc0df856b948
Create Date: 2026-08-20 10:52:52.846671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2e7905869f'
down_revision: Union[str, Sequence[str], None] = 'fc0df856b948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('risk_level_ai_model', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('pedagogical_category_ai_model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'pedagogical_category_ai_model')
    op.drop_column('comments', 'risk_level_ai_model')
    # ### end Alembic commands ###
