"""remove institutional_code in users

Revision ID: 457dc54b4019
Revises: b28243a7e693
Create Date: 2026-06-08 10:43:15.586899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457dc54b4019'
down_revision: Union[str, Sequence[str], None] = 'b28243a7e693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_institutional_code_key'), 'users', type_='unique')
    op.drop_column('users', 'institutional_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('institutional_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_institutional_code_key'), 'users', ['institutional_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
