"""comment pedagogical categories many to many

Revision ID: 493281df65d4
Revises: 08f60f3e3cbc
Create Date: 2026-08-11 20:42:52.005986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493281df65d4'
down_revision: Union[str, Sequence[str], None] = '08f60f3e3cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Table may already exist if create_all ran before this migration was added.
    if 'comment_pedagogical_categories' not in inspector.get_table_names():
        op.create_table('comment_pedagogical_categories',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('comment_id', sa.Integer(), nullable=False),
        sa.Column('pedagogical_category_id', sa.Integer(), nullable=False),
        sa.Column('score', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['pedagogical_category_id'], ['pedagogical_categories.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_comment_pedagogical_categories_comment_id'), 'comment_pedagogical_categories', ['comment_id'], unique=False)
        op.create_index(op.f('ix_comment_pedagogical_categories_id'), 'comment_pedagogical_categories', ['id'], unique=False)
        op.create_index(op.f('ix_comment_pedagogical_categories_pedagogical_category_id'), 'comment_pedagogical_categories', ['pedagogical_category_id'], unique=False)

    # Migrate data and drop old columns only if they still exist on comments.
    existing_cols = {c['name'] for c in inspector.get_columns('comments')}
    if 'pedagogical_category_id' in existing_cols:
        op.execute(
            """
            INSERT INTO comment_pedagogical_categories (comment_id, pedagogical_category_id, score)
            SELECT id, pedagogical_category_id, category_score
            FROM comments
            WHERE pedagogical_category_id IS NOT NULL
            """
        )
        op.drop_constraint(op.f('comments_pedagogical_category_id_fkey'), 'comments', type_='foreignkey')
        op.drop_column('comments', 'category_score')
        op.drop_column('comments', 'pedagogical_category_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pedagogical_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('category_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('comments_pedagogical_category_id_fkey'), 'comments', 'pedagogical_categories', ['pedagogical_category_id'], ['id'])

    # Best effort: restore one (arbitrary, highest-score) category per comment.
    # Any comment left with 2+ categories loses the rest — inherent to collapsing
    # a many-to-many back into a single column.
    op.execute(
        """
        UPDATE comments c
        SET pedagogical_category_id = sub.pedagogical_category_id,
            category_score = sub.score
        FROM (
            SELECT DISTINCT ON (comment_id) comment_id, pedagogical_category_id, score
            FROM comment_pedagogical_categories
            ORDER BY comment_id, score DESC NULLS LAST
        ) sub
        WHERE c.id = sub.comment_id
        """
    )

    op.drop_index(op.f('ix_comment_pedagogical_categories_pedagogical_category_id'), table_name='comment_pedagogical_categories')
    op.drop_index(op.f('ix_comment_pedagogical_categories_id'), table_name='comment_pedagogical_categories')
    op.drop_index(op.f('ix_comment_pedagogical_categories_comment_id'), table_name='comment_pedagogical_categories')
    op.drop_table('comment_pedagogical_categories')
    # ### end Alembic commands ###
