"""add risk_score and category_score to comments

Revision ID: 57e59c0f5b4a
Revises: 5bb9c233abb3
Create Date: 2026-07-14 21:52:17.397933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e59c0f5b4a'
down_revision: Union[str, Sequence[str], None] = '5bb9c233abb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('comments', sa.Column('category_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'category_score')
    op.drop_column('comments', 'risk_score')
    # ### end Alembic commands ###
