"""add director modification flags to comments

Revision ID: 7b5bce8aad0d
Revises: b63856ef16c6
Create Date: 2026-08-08 17:57:16.436633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5bce8aad0d'
down_revision: Union[str, Sequence[str], None] = 'b63856ef16c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required so existing rows get a value for the new
    # NOT NULL columns; it matches the model's Python-side default=False.
    op.add_column(
        'comments',
        sa.Column(
            'risk_level_modified_by_director',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )
    op.add_column(
        'comments',
        sa.Column(
            'pedagogical_category_modified_by_director',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )
    op.alter_column('comments', 'risk_level_modified_by_director', server_default=None)
    op.alter_column(
        'comments', 'pedagogical_category_modified_by_director', server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'pedagogical_category_modified_by_director')
    op.drop_column('comments', 'risk_level_modified_by_director')
    # ### end Alembic commands ###
