"""relations_courses_groups

Revision ID: ab815a23440b
Revises: f8b6d23bb6b7
Create Date: 2026-07-21 10:26:52.696298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab815a23440b'
down_revision: Union[str, Sequence[str], None] = 'f8b6d23bb6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directors_department_id'), 'directors', ['department_id'], unique=True)
    op.create_index(op.f('ix_directors_id'), 'directors', ['id'], unique=False)
    op.create_index(op.f('ix_directors_user_id'), 'directors', ['user_id'], unique=True)
    op.create_unique_constraint('uq_academic_groups_course_teacher_period_name', 'academic_groups', ['course_id', 'teacher_id', 'academic_period_id', 'group_name'])
    op.drop_constraint(op.f('users_department_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_department_id_fkey'), 'users', 'departments', ['department_id'], ['id'])
    op.drop_constraint('uq_academic_groups_course_teacher_period_name', 'academic_groups', type_='unique')
    op.drop_index(op.f('ix_directors_user_id'), table_name='directors')
    op.drop_index(op.f('ix_directors_id'), table_name='directors')
    op.drop_index(op.f('ix_directors_department_id'), table_name='directors')
    op.drop_table('directors')
    # ### end Alembic commands ###
