"""add_active_column_to_evaluations

Revision ID: b014bffa99a0
Revises: b3f6d9a1c2ef
Create Date: 2026-06-24 14:49:15.305624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b014bffa99a0'
down_revision: Union[str, Sequence[str], None] = 'b3f6d9a1c2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'active')
    # ### end Alembic commands ###
