"""add_element_and_description_to_audit

Revision ID: d13dc8159654
Revises: b014bffa99a0
Create Date: 2026-06-24 16:23:52.799183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13dc8159654'
down_revision: Union[str, Sequence[str], None] = 'b014bffa99a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit', sa.Column('element', sa.String(length=255), nullable=True))
    op.add_column('audit', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit', 'description')
    op.drop_column('audit', 'element')
    # ### end Alembic commands ###
