"""update dates in audit table

Revision ID: e39c7fb9c67b
Revises: 457dc54b4019
Create Date: 2026-06-08 10:49:44.989032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39c7fb9c67b'
down_revision: Union[str, Sequence[str], None] = '457dc54b4019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('audit', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=True)
    op.drop_column('audit', 'updated_at')
    # ### end Alembic commands ###
