"""add improvement_plans tables

Revision ID: f484d9628fbd
Revises: fefdec36bfed
Create Date: 2026-07-12 19:16:13.399945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f484d9628fbd'
down_revision: Union[str, Sequence[str], None] = 'fefdec36bfed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('improvement_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('origin_period_id', sa.Integer(), nullable=False),
    sa.Column('verification_period_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('close_reason', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['origin_period_id'], ['academic_periods.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['verification_period_id'], ['academic_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_improvement_plans_id'), 'improvement_plans', ['id'], unique=False)
    op.create_index(op.f('ix_improvement_plans_teacher_id'), 'improvement_plans', ['teacher_id'], unique=False)
    op.create_table('improvement_plan_checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['improvement_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_improvement_plan_checkpoints_id'), 'improvement_plan_checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_improvement_plan_checkpoints_plan_id'), 'improvement_plan_checkpoints', ['plan_id'], unique=False)
    op.create_table('improvement_plan_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_ref', sa.String(length=255), nullable=True),
    sa.Column('baseline_value', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('result_value', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['improvement_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_improvement_plan_items_id'), 'improvement_plan_items', ['id'], unique=False)
    op.create_index(op.f('ix_improvement_plan_items_plan_id'), 'improvement_plan_items', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_improvement_plan_items_plan_id'), table_name='improvement_plan_items')
    op.drop_index(op.f('ix_improvement_plan_items_id'), table_name='improvement_plan_items')
    op.drop_table('improvement_plan_items')
    op.drop_index(op.f('ix_improvement_plan_checkpoints_plan_id'), table_name='improvement_plan_checkpoints')
    op.drop_index(op.f('ix_improvement_plan_checkpoints_id'), table_name='improvement_plan_checkpoints')
    op.drop_table('improvement_plan_checkpoints')
    op.drop_index(op.f('ix_improvement_plans_teacher_id'), table_name='improvement_plans')
    op.drop_index(op.f('ix_improvement_plans_id'), table_name='improvement_plans')
    op.drop_table('improvement_plans')
    # ### end Alembic commands ###
