"""remove_departament_id_in_users

Revision ID: f8b6d23bb6b7
Revises: 57e59c0f5b4a
Create Date: 2026-07-16 18:55:39.924066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8b6d23bb6b7'
down_revision: Union[str, Sequence[str], None] = '57e59c0f5b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_directors_department_id'), table_name='directors')
    # op.drop_index(op.f('ix_directors_id'), table_name='directors')
    # op.drop_index(op.f('ix_directors_user_id'), table_name='directors')
    # op.drop_table('directors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('directors_department_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('directors_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('directors_pkey'))
    )
    op.create_index(op.f('ix_directors_user_id'), 'directors', ['user_id'], unique=True)
    op.create_index(op.f('ix_directors_id'), 'directors', ['id'], unique=False)
    op.create_index(op.f('ix_directors_department_id'), 'directors', ['department_id'], unique=True)
    # ### end Alembic commands ###
