"""add risk_levels and pedagogical_categories tables and fk constraints on comments

Revision ID: fefdec36bfed
Revises: 63ce65be4a16
Create Date: 2026-07-11 12:04:03.616478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fefdec36bfed'
down_revision: Union[str, Sequence[str], None] = '63ce65be4a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedagogical_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_hex', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedagogical_categories_id'), 'pedagogical_categories', ['id'], unique=False)
    op.create_table('risk_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_hex', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_levels_id'), 'risk_levels', ['id'], unique=False)
    op.create_foreign_key(None, 'comments', 'pedagogical_categories', ['pedagogical_category_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'risk_levels', ['risk_level'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_risk_levels_id'), table_name='risk_levels')
    op.drop_table('risk_levels')
    op.drop_index(op.f('ix_pedagogical_categories_id'), table_name='pedagogical_categories')
    op.drop_table('pedagogical_categories')
    # ### end Alembic commands ###
