"""Baseline (read-only) load test against the local stress-test container.

Deliberately starts with cheap, simple GET endpoints (no PDF upload, no AI
analysis) to get a clean baseline before stressing the heavier flows. Each
simulated user picks a random real uid for its role from
loadtest/stress_users.json (generated by list_stress_users.py) and sends it
via X-Test-Uid, which loadtest/asgi_stress.py trusts instead of a real
Firebase token — role checks in `require_roles` still run for real against
the isolated test database.

Needs Locust, which isn't a project dependency (dev/test-only, never runs in
the app itself): ./venv/bin/pip install locust

Run against the container from docker-compose.stress.yaml (default port
8090):

    locust -f loadtest/locustfile.py --host http://localhost:8090

or headless with a report:

    locust -f loadtest/locustfile.py --headless -u 50 -r 5 -t 5m \
        --host http://localhost:8090 --html reporte.html --csv resultados
"""

import json
import random
from pathlib import Path

from locust import HttpUser, task, between

USERS_FILE = Path(__file__).resolve().parent / "stress_users.json"
DOCENTE_TEACHERS_FILE = Path(__file__).resolve().parent / "docente_teacher_ids.json"

try:
    _UIDS_BY_ROLE = json.loads(USERS_FILE.read_text(encoding="utf-8"))
except FileNotFoundError as exc:
    raise SystemExit(
        f"{USERS_FILE} no existe. Corre primero: "
        "./venv/bin/python loadtest/list_stress_users.py"
    ) from exc

# uid -> {"teacher_id": int, "course_code": str}, for the DOCENTE self-service
# endpoints (grades, own course, own plans) that need more than just a uid —
# a DOCENTE can only see their own teacher_id, so uid and teacher_id must be
# picked together, not independently.
_DOCENTE_TEACHERS = json.loads(DOCENTE_TEACHERS_FILE.read_text(encoding="utf-8"))


def _random_uid(role: str) -> str:
    uids = _UIDS_BY_ROLE.get(role)
    if not uids:
        raise SystemExit(f"No hay uids para el rol {role!r} en {USERS_FILE}")
    return random.choice(uids)


def _random_docente_teacher() -> tuple[str, int, str]:
    uid = random.choice(list(_DOCENTE_TEACHERS.keys()))
    info = _DOCENTE_TEACHERS[uid]
    return uid, info["teacher_id"], info["course_code"]


class AdminUser(HttpUser):
    """Read-only ADMIN traffic: catalogs and org-wide reads.

    Weight matches the SLA peak mix agreed with the project owner: 1 ADMIN +
    7 DIRECTOR + 20 DOCENTE = 28 concurrent, so `-u 28` reproduces that exact
    composition instead of an arbitrary ratio.
    """

    weight = 1
    wait_time = between(1, 3)

    def on_start(self):
        self.client.headers["X-Test-Uid"] = _random_uid("ADMIN")

    @task(2)
    def list_departments(self):
        self.client.get("/departments/", name="/departments/")

    @task(3)
    def list_teachers(self):
        self.client.get("/teachers/", name="/teachers/")

    @task(1)
    def department_averages(self):
        self.client.get("/stats/departments/averages", name="/stats/departments/averages")


class DirectorUser(HttpUser):
    """Read-only DIRECTOR DE DEPARTAMENTO traffic: their own department's data."""

    weight = 7
    wait_time = between(1, 3)

    def on_start(self):
        self.client.headers["X-Test-Uid"] = _random_uid("DIRECTOR DE DEPARTAMENTO")

    @task(3)
    def list_teachers(self):
        self.client.get("/teachers/", name="/teachers/")

    @task(2)
    def department_averages(self):
        self.client.get("/stats/departments/averages", name="/stats/departments/averages")

    @task(2)
    def my_notifications(self):
        self.client.get("/notifications/me", name="/notifications/me")

    @task(1)
    def academic_periods(self):
        self.client.get("/academic-periods/", name="/academic-periods/")


class DocenteUser(HttpUser):
    """DOCENTE traffic: notifications plus the self-service "check my own
    results" flow (grades, own course history, own improvement plans) — the
    scenario that matters most in practice, since it's what spikes right
    after evaluation results are published."""

    weight = 20
    wait_time = between(1, 3)

    def on_start(self):
        uid, teacher_id, course_code = _random_docente_teacher()
        self.client.headers["X-Test-Uid"] = uid
        self.teacher_id = teacher_id
        self.course_code = course_code

    @task(3)
    def my_notifications(self):
        self.client.get("/notifications/me", name="/notifications/me")

    @task(2)
    def unread_count(self):
        self.client.get("/notifications/me/unread-count", name="/notifications/me/unread-count")

    @task(1)
    def academic_periods(self):
        self.client.get("/academic-periods/", name="/academic-periods/")

    @task(3)
    def my_grades(self):
        self.client.get(f"/teachers/{self.teacher_id}/history", name="/teachers/{id}/history")

    @task(2)
    def my_course(self):
        self.client.get(
            f"/teachers/{self.teacher_id}/courses/{self.course_code}/history",
            name="/teachers/{id}/courses/{code}/history",
        )

    @task(2)
    def my_improvement_plans(self):
        self.client.get("/improvement-plans/my", name="/improvement-plans/my")
